### ISSUE TITLE
UnicodeDecodeError while reading a Dota2 VPK file.

### ISSUE THREAD

**Issue by TimotheeJeannin** [ValvePython/vpk#3]
I'm trying to read a Dota2 vpk file like this:

```python
import vpk

pak1 = vpk.open("/media/tim/Data1/SteamLibrary/steamapps/common/dota 2 beta/game/dota/pak01_002.vpk")

for filepath in pak1:
    print filepath
```

But I get this error:

    Traceback (most recent call last):
      File "match_processor/ok.py", line 3, in <module>
        pak1 = vpk.open("/media/tim/Data1/SteamLibrary/steamapps/common/dota 2 beta/game/dota/pak01_002.vpk")
      File "/home/tim/Workspace/dota_memories/match_processor/env/local/lib/python2.7/site-packages/vpk/__init__.py", line 15, in open
        return VPK(vpk_path, **kwargs)
      File "/home/tim/Workspace/dota_memories/match_processor/env/local/lib/python2.7/site-packages/vpk/__init__.py", line 190, in __init__
        self.read_index()
      File "/home/tim/Workspace/dota_memories/match_processor/env/local/lib/python2.7/site-packages/vpk/__init__.py", line 311, in read_index
        ext = self._read_sz(f)
      File "/home/tim/Workspace/dota_memories/match_processor/env/local/lib/python2.7/site-packages/vpk/__init__.py", line 227, in _read_sz
        return buf.decode('ascii')
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 1: ordinal not in range(128)

Am I doing something wrong ?

**Comment by rossengeorgiev** [comment]
Yep. You need to open `pak01_dir.vpk`. That's the index. All `pak01_0xx.vpk` file are the data and cannot be opened directly. All those files are essentially one giant vpk.

**Comment by TimotheeJeannin** [comment]
Ha ok ! Thank you for your quick response ! :)
